/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TsqRouteRouteImport } from './routes/tsq/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TsqIndexRouteImport } from './routes/tsq/index'
import { Route as TsqRecipesIndexRouteImport } from './routes/tsq/recipes/index'
import { Route as TsqIngredientsIndexRouteImport } from './routes/tsq/ingredients/index'
import { Route as TsqRecipesIdRouteImport } from './routes/tsq/recipes/$id'
import { Route as TsqIngredientsIdRouteImport } from './routes/tsq/ingredients/$id'

const TsqRouteRoute = TsqRouteRouteImport.update({
  id: '/tsq',
  path: '/tsq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TsqIndexRoute = TsqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TsqRouteRoute,
} as any)
const TsqRecipesIndexRoute = TsqRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => TsqRouteRoute,
} as any)
const TsqIngredientsIndexRoute = TsqIngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => TsqRouteRoute,
} as any)
const TsqRecipesIdRoute = TsqRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => TsqRouteRoute,
} as any)
const TsqIngredientsIdRoute = TsqIngredientsIdRouteImport.update({
  id: '/ingredients/$id',
  path: '/ingredients/$id',
  getParentRoute: () => TsqRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tsq': typeof TsqRouteRouteWithChildren
  '/tsq/': typeof TsqIndexRoute
  '/tsq/ingredients/$id': typeof TsqIngredientsIdRoute
  '/tsq/recipes/$id': typeof TsqRecipesIdRoute
  '/tsq/ingredients/': typeof TsqIngredientsIndexRoute
  '/tsq/recipes/': typeof TsqRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tsq': typeof TsqIndexRoute
  '/tsq/ingredients/$id': typeof TsqIngredientsIdRoute
  '/tsq/recipes/$id': typeof TsqRecipesIdRoute
  '/tsq/ingredients': typeof TsqIngredientsIndexRoute
  '/tsq/recipes': typeof TsqRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tsq': typeof TsqRouteRouteWithChildren
  '/tsq/': typeof TsqIndexRoute
  '/tsq/ingredients/$id': typeof TsqIngredientsIdRoute
  '/tsq/recipes/$id': typeof TsqRecipesIdRoute
  '/tsq/ingredients/': typeof TsqIngredientsIndexRoute
  '/tsq/recipes/': typeof TsqRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tsq'
    | '/tsq/'
    | '/tsq/ingredients/$id'
    | '/tsq/recipes/$id'
    | '/tsq/ingredients/'
    | '/tsq/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tsq'
    | '/tsq/ingredients/$id'
    | '/tsq/recipes/$id'
    | '/tsq/ingredients'
    | '/tsq/recipes'
  id:
    | '__root__'
    | '/'
    | '/tsq'
    | '/tsq/'
    | '/tsq/ingredients/$id'
    | '/tsq/recipes/$id'
    | '/tsq/ingredients/'
    | '/tsq/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TsqRouteRoute: typeof TsqRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tsq': {
      id: '/tsq'
      path: '/tsq'
      fullPath: '/tsq'
      preLoaderRoute: typeof TsqRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tsq/': {
      id: '/tsq/'
      path: '/'
      fullPath: '/tsq/'
      preLoaderRoute: typeof TsqIndexRouteImport
      parentRoute: typeof TsqRouteRoute
    }
    '/tsq/recipes/': {
      id: '/tsq/recipes/'
      path: '/recipes'
      fullPath: '/tsq/recipes/'
      preLoaderRoute: typeof TsqRecipesIndexRouteImport
      parentRoute: typeof TsqRouteRoute
    }
    '/tsq/ingredients/': {
      id: '/tsq/ingredients/'
      path: '/ingredients'
      fullPath: '/tsq/ingredients/'
      preLoaderRoute: typeof TsqIngredientsIndexRouteImport
      parentRoute: typeof TsqRouteRoute
    }
    '/tsq/recipes/$id': {
      id: '/tsq/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/tsq/recipes/$id'
      preLoaderRoute: typeof TsqRecipesIdRouteImport
      parentRoute: typeof TsqRouteRoute
    }
    '/tsq/ingredients/$id': {
      id: '/tsq/ingredients/$id'
      path: '/ingredients/$id'
      fullPath: '/tsq/ingredients/$id'
      preLoaderRoute: typeof TsqIngredientsIdRouteImport
      parentRoute: typeof TsqRouteRoute
    }
  }
}

interface TsqRouteRouteChildren {
  TsqIndexRoute: typeof TsqIndexRoute
  TsqIngredientsIdRoute: typeof TsqIngredientsIdRoute
  TsqRecipesIdRoute: typeof TsqRecipesIdRoute
  TsqIngredientsIndexRoute: typeof TsqIngredientsIndexRoute
  TsqRecipesIndexRoute: typeof TsqRecipesIndexRoute
}

const TsqRouteRouteChildren: TsqRouteRouteChildren = {
  TsqIndexRoute: TsqIndexRoute,
  TsqIngredientsIdRoute: TsqIngredientsIdRoute,
  TsqRecipesIdRoute: TsqRecipesIdRoute,
  TsqIngredientsIndexRoute: TsqIngredientsIndexRoute,
  TsqRecipesIndexRoute: TsqRecipesIndexRoute,
}

const TsqRouteRouteWithChildren = TsqRouteRoute._addFileChildren(
  TsqRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TsqRouteRoute: TsqRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
